---
engines:
  brakeman:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
  rubocop:
    enabled: true
ratings:
  paths:
  - Gemfile.lock
  - "**.rb"
exclude_paths:
- config/
- db/
- spec/
- vendor/
