default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: job_tracker_development

test:
  <<: *default
  database: job_tracker_test

production:
  <<: *default
  database: job_tracker_production
