require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe InteractionsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Interaction. As you add validations to Interaction, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # InteractionsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all interactions as @interactions" do
      interaction = Interaction.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:interactions)).to eq([interaction])
    end
  end

  describe "GET #show" do
    it "assigns the requested interaction as @interaction" do
      interaction = Interaction.create! valid_attributes
      get :show, {:id => interaction.to_param}, valid_session
      expect(assigns(:interaction)).to eq(interaction)
    end
  end

  describe "GET #new" do
    it "assigns a new interaction as @interaction" do
      get :new, {}, valid_session
      expect(assigns(:interaction)).to be_a_new(Interaction)
    end
  end

  describe "GET #edit" do
    it "assigns the requested interaction as @interaction" do
      interaction = Interaction.create! valid_attributes
      get :edit, {:id => interaction.to_param}, valid_session
      expect(assigns(:interaction)).to eq(interaction)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Interaction" do
        expect {
          post :create, {:interaction => valid_attributes}, valid_session
        }.to change(Interaction, :count).by(1)
      end

      it "assigns a newly created interaction as @interaction" do
        post :create, {:interaction => valid_attributes}, valid_session
        expect(assigns(:interaction)).to be_a(Interaction)
        expect(assigns(:interaction)).to be_persisted
      end

      it "redirects to the created interaction" do
        post :create, {:interaction => valid_attributes}, valid_session
        expect(response).to redirect_to(Interaction.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved interaction as @interaction" do
        post :create, {:interaction => invalid_attributes}, valid_session
        expect(assigns(:interaction)).to be_a_new(Interaction)
      end

      it "re-renders the 'new' template" do
        post :create, {:interaction => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested interaction" do
        interaction = Interaction.create! valid_attributes
        put :update, {:id => interaction.to_param, :interaction => new_attributes}, valid_session
        interaction.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested interaction as @interaction" do
        interaction = Interaction.create! valid_attributes
        put :update, {:id => interaction.to_param, :interaction => valid_attributes}, valid_session
        expect(assigns(:interaction)).to eq(interaction)
      end

      it "redirects to the interaction" do
        interaction = Interaction.create! valid_attributes
        put :update, {:id => interaction.to_param, :interaction => valid_attributes}, valid_session
        expect(response).to redirect_to(interaction)
      end
    end

    context "with invalid params" do
      it "assigns the interaction as @interaction" do
        interaction = Interaction.create! valid_attributes
        put :update, {:id => interaction.to_param, :interaction => invalid_attributes}, valid_session
        expect(assigns(:interaction)).to eq(interaction)
      end

      it "re-renders the 'edit' template" do
        interaction = Interaction.create! valid_attributes
        put :update, {:id => interaction.to_param, :interaction => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested interaction" do
      interaction = Interaction.create! valid_attributes
      expect {
        delete :destroy, {:id => interaction.to_param}, valid_session
      }.to change(Interaction, :count).by(-1)
    end

    it "redirects to the interactions list" do
      interaction = Interaction.create! valid_attributes
      delete :destroy, {:id => interaction.to_param}, valid_session
      expect(response).to redirect_to(interactions_url)
    end
  end

end
